---
- name: use motd role playbook
  hosts: 192.168.0.154
  become: true

- name: deliver motd file
  template:
    src: /root/system-motd/templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0444

